# Generated by Django 2.1 on 2018-08-10 14:33

import datetime
import django.core.files.storage
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='valor',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='variable',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='externo',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Creación'),
        ),
        migrations.AddField(
            model_name='externo',
            name='file',
            field=models.FileField(null=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\salvar\\djangogirls\\static\\store'), upload_to=''),
        ),
        migrations.AddField(
            model_name='externo',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='externo',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(1900, 1, 1, 0, 0), verbose_name='Última Actualización'),
        ),
        migrations.AddField(
            model_name='externo',
            name='url',
            field=models.URLField(default='', max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='myurls',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='myurls',
            name='password',
            field=models.CharField(default='', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='myurls',
            name='url',
            field=models.URLField(default='', max_length=128, unique=True),
        ),
        migrations.AddField(
            model_name='myurls',
            name='usuario',
            field=models.CharField(default='', max_length=128, null=True),
        ),
    ]
