# Generated by Django 2.1 on 2018-08-15 19:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20180810_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('ref', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('html_description', models.TextField(blank=True, null=True)),
                ('product_url', models.URLField(blank=True, null=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Última Actualización')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('release_date', models.DateTimeField(blank=True, null=True, verbose_name='Lanzamiento')),
                ('available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('destocking', models.BooleanField(default=False, verbose_name='Liquidación')),
                ('sale', models.BooleanField(default=False, verbose_name='Rebajado')),
                ('new', models.BooleanField(default=True, verbose_name='Nuevo')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('recommended_retail_price', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('default_shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('delivery_desc', models.CharField(blank=True, max_length=20)),
                ('vat', models.DecimalField(decimal_places=2, default=21.0, max_digits=4, verbose_name='IVA')),
                ('unit_of_measurement', models.CharField(blank=True, max_length=20)),
                ('pvp', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('stock', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ('-release_date',),
            },
        ),
        migrations.AlterModelOptions(
            name='myurls',
            options={'ordering': ('name', 'usuario')},
        ),
    ]
