# Generated by Django 2.1 on 2018-08-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20180817_1027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150)),
                ('activo', models.BooleanField(default=True)),
                ('gesioid', models.IntegerField(null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Categorias',
                'ordering': ('name',),
            },
        ),
    ]
