# Generated by Django 2.1 on 2018-08-20 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_category_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myurls',
            options={'ordering': ('name', 'usuario'), 'verbose_name_plural': 'Mis URLs'},
        ),
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.ManyToManyField(to='shop.Category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_ppal', to='shop.Category'),
        ),
    ]
