# Generated by Django 2.1 on 2018-08-20 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20180820_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='fabricante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fabricante', to='shop.Category'),
        ),
    ]
