# Generated by Django 2.1 on 2018-08-20 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_product_fabricante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='gesioid',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='shop.Category'),
        ),
    ]
