# Generated by Django 2.1 on 2018-08-27 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_auto_20180821_1325'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='imagen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='portada', to='shop.Imagen'),
        ),
        migrations.AlterField(
            model_name='myurls',
            name='password',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='myurls',
            name='usuario',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_ppal', to='shop.Category'),
        ),
    ]
